import { useState } from "react";
import { useNavigate } from "react-router-dom";
import PageHeader from "../components/common/PageHeader";
import Icon from "../components/common/Icon";
import { apiRequest } from "../services/api";

export default function UploadPage() {
  const navigate = useNavigate();
  const [form, setForm] = useState({ title: "", description: "", videoFile: null, thumbnail: null });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  function update(event) { const { name, value, files } = event.target; setForm((current) => ({ ...current, [name]: files ? files[0] : value })); }
  async function submit(event) { event.preventDefault(); setError(""); setLoading(true); try { const body = new FormData(); body.append("title", form.title); body.append("description", form.description); body.append("videoFile", form.videoFile); body.append("thumbnail", form.thumbnail); await apiRequest("/videos", { method: "POST", body }); navigate("/dashboard"); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } }
  return <main className="content-page upload-page"><PageHeader eyebrow="Creator studio" title="Put something good into the world." description="Tell a story, teach a skill, or make someone’s day a little more interesting." /><form className="upload-form" onSubmit={submit}>{error && <div className="form-error">{error}</div>}<div className="upload-fields"><label>Video title<input name="title" value={form.title} onChange={update} placeholder="Give your video a clear, memorable title" required /></label><label>Description<textarea name="description" value={form.description} onChange={update} rows="6" placeholder="What should viewers know before they press play?" required /></label><div className="file-drop-grid"><label className={`file-drop ${form.videoFile ? "file-selected" : ""}`}><Icon name="upload" size={24} /><strong>{form.videoFile ? form.videoFile.name : "Choose your video"}</strong><span>MP4, MOV or WebM · up to 2GB</span><input name="videoFile" type="file" accept="video/*" onChange={update} required /></label><label className={`file-drop ${form.thumbnail ? "file-selected" : ""}`}><Icon name="compass" size={24} /><strong>{form.thumbnail ? form.thumbnail.name : "Add a thumbnail"}</strong><span>JPG or PNG · helps people find you</span><input name="thumbnail" type="file" accept="image/*" onChange={update} required /></label></div></div><aside className="upload-side"><div className="upload-preview"><span className="preview-label">Preview</span>{form.thumbnail ? <img src={URL.createObjectURL(form.thumbnail)} alt="Thumbnail preview" /> : <div><Icon name="play" size={28} /><p>Your thumbnail<br />will appear here</p></div>}</div><div className="publish-note"><span>✦</span><p><strong>Make it yours.</strong><br />Your video will be published as soon as it finishes uploading.</p></div></aside><div className="upload-actions"><button type="button" className="button button-secondary" onClick={() => navigate(-1)}>Cancel</button><button className="button button-primary" disabled={loading}>{loading ? "Uploading…" : "Publish video"}<Icon name="arrow" size={16} /></button></div></form></main>;
}
